package edu.snhu.dayplanner.control;

import edu.snhu.dayplanner.ui.NavigationView;
import javafx.scene.Parent;

/**
 * Responsible for initializing the main application user interface and navigation logic for transitioning to each
 * screen. Provides functionality to {@code NavigationView} buttons which replace center view of layout.
 *  @author Michael Lorenz
 *  @version 1.0, 1/25/2025
 */
public class NavController {
    private final NavigationView navView;
    ContactController contactController;
    TaskController taskController;
    AppointmentController appointmentController;

    /**
     * Initializes a new {@code NavigationView} object and each controller used for every screen of the application.
     * Sets action listeners to navigation sidebar buttons.
     */
    public NavController() {
        navView = new NavigationView();
        contactController = new ContactController();
        taskController = new TaskController();
        appointmentController = new AppointmentController();

        navView.getContactButton().setOnAction(event -> {
            navView.selectButton(navView.getContactButton());
            navView.setCenterView(contactController.getView());

        });

        navView.getTaskButton().setOnAction(event -> {
            navView.selectButton(navView.getTaskButton());
            navView.setCenterView(taskController.getView());
        });

        navView.getAppointmentButton().setOnAction(event -> {
            navView.selectButton(navView.getAppointmentButton());
            navView.setCenterView(appointmentController.getView());
        });
    }

    /**
     * @return the root view generated by {@code NavigationView} displaying the application interface
     */
    public Parent getNavView() {
        return navView.getView();
    }
}
